// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: cosik

#include "ui.h"
#include <Arduino.h>

void disconnectWiFi(lv_event_t * e);

void connectWiFi(lv_event_t * e);

