// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: cosik

#ifndef UI_SERIALTERM_H
#define UI_SERIALTERM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_serialTerm
bool terminal_screen_active = false;
extern void ui_serialTerm_screen_init(void);
extern void ui_serialTerm_screen_destroy(void);
extern void ui_event_serialTerm(lv_event_t * e);
extern lv_obj_t * ui_serialTerm;
extern lv_obj_t * ui_status;
extern lv_obj_t * ui_clock;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_wifistr;
extern lv_obj_t * ui_wifistat;
extern lv_obj_t * ui_appname;
extern lv_obj_t * ui_apps;
extern lv_obj_t * ui_serial;
extern void ui_event_wifi(lv_event_t * e);
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_content;
extern void ui_event_Keyboard2(lv_event_t * e);
extern lv_obj_t * ui_Keyboard2;
extern void ui_event_Input(lv_event_t * e);
extern lv_obj_t * ui_Input;
extern void ui_event_output(lv_event_t * e);
extern lv_obj_t * ui_output;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_serialPrefs;
extern lv_obj_t * ui_baudrate;
extern lv_obj_t * ui_serialset;
extern void ui_event_SerialSetAccept(lv_event_t * e);
extern lv_obj_t * ui_SerialSetAccept;
extern lv_obj_t * ui_okBtnLabel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_serialTerm;
extern lv_obj_t * uic_status;
extern lv_obj_t * uic_clock;
extern lv_obj_t * uic_wifistat;
extern lv_obj_t * uic_appname;
extern lv_obj_t * uic_apps;
extern lv_obj_t * uic_serial;
extern lv_obj_t * uic_wifi;
extern lv_obj_t * uic_content;
extern lv_obj_t * uic_Input;
extern lv_obj_t * uic_output;
extern lv_obj_t * uic_serialPrefs;
extern lv_obj_t * uic_baudrate;
extern lv_obj_t * uic_serialset;
extern lv_obj_t * uic_SerialSetAccept;
extern lv_obj_t * uic_okBtnLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

