// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: cosik

#include "ui.h"

lv_obj_t * uic_okBtnLabel;
lv_obj_t * uic_SerialSetAccept;
lv_obj_t * uic_serialset;
lv_obj_t * uic_baudrate;
lv_obj_t * uic_serialPrefs;
lv_obj_t * uic_output;
lv_obj_t * uic_Input;
lv_obj_t * uic_content;
lv_obj_t * uic_wifi;
lv_obj_t * uic_serial;
lv_obj_t * uic_apps;
lv_obj_t * uic_appname;
lv_obj_t * uic_wifistat;
lv_obj_t * uic_clock;
lv_obj_t * uic_status;
lv_obj_t * uic_serialTerm;
lv_obj_t * ui_serialTerm = NULL;
lv_obj_t * ui_status = NULL;
lv_obj_t * ui_clock = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_wifistr = NULL;
lv_obj_t * ui_wifistat = NULL;
lv_obj_t * ui_appname = NULL;
lv_obj_t * ui_apps = NULL;
lv_obj_t * ui_serial = NULL;
lv_obj_t * ui_wifi = NULL;
lv_obj_t * ui_content = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_Input = NULL;
lv_obj_t * ui_output = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_serialPrefs = NULL;
lv_obj_t * ui_baudrate = NULL;
lv_obj_t * ui_serialset = NULL;
lv_obj_t * ui_SerialSetAccept = NULL;
lv_obj_t * ui_okBtnLabel = NULL;
// event funtions
void ui_event_serialTerm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_flag_modify(ui_Container3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_wifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiSettings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WifiSettings_screen_init);
    }
}

void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        SerialWrite(e);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ESC) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Input(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_output, _UI_BASIC_PROPERTY_HEIGHT,  140);
    }
}

void ui_event_output(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_basic_set_property(ui_output, _UI_BASIC_PROPERTY_HEIGHT,  350);
    }
}

void ui_event_SerialSetAccept(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SetupSerial(e);
        _ui_flag_modify(ui_Container3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_serialTerm_screen_init(void)
{
    terminal_screen_active = true;
    ui_serialTerm = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_serialTerm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_serialTerm, &ui_img_backblue800x480_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status = lv_obj_create(ui_serialTerm);
    lv_obj_set_width(ui_status, 800);
    lv_obj_set_height(ui_status, 40);
    lv_obj_set_align(ui_status, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_status, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_status, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_status, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_status, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_status, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_status, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clock = lv_label_create(ui_status);
    lv_obj_set_width(ui_clock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clock, "%clock%");
    lv_obj_set_style_text_color(ui_clock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_clock, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clock, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_status);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 150);
    lv_obj_set_height(ui_Container1, 40);
    lv_obj_set_x(ui_Container1, 20);
    lv_obj_set_y(ui_Container1, 0);
    lv_obj_set_align(ui_Container1, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifistr = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_wifistr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifistr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifistr, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_wifistr, "%wifi%");
    lv_obj_set_style_text_color(ui_wifistr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifistr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_wifistr, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifistr, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifistat = lv_img_create(ui_Container1);
    lv_img_set_src(ui_wifistat, &ui_img_1149142576);
    lv_obj_set_width(ui_wifistat, 32);
    lv_obj_set_height(ui_wifistat, 32);
    lv_obj_set_align(ui_wifistat, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_wifistat, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifistat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_appname = lv_label_create(ui_status);
    lv_obj_set_width(ui_appname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_appname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_appname, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_appname, "Serial Terminal");
    lv_obj_set_style_text_color(ui_appname, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_appname, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_appname, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_appname, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_apps = lv_obj_create(ui_serialTerm);
    lv_obj_set_width(ui_apps, 90);
    lv_obj_set_height(ui_apps, 430);
    lv_obj_set_x(ui_apps, 0);
    lv_obj_set_y(ui_apps, 20);
    lv_obj_set_align(ui_apps, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_apps, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_apps, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_apps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_apps, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_apps, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_apps, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_apps, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_apps, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_apps, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_apps, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_serial = lv_imgbtn_create(ui_apps);
    lv_imgbtn_set_src(ui_serial, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1659073291, NULL);
    lv_imgbtn_set_src(ui_serial, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1659073291, NULL);
    lv_imgbtn_set_src(ui_serial, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_1659073291, NULL);
    lv_imgbtn_set_src(ui_serial, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_1659073291, NULL);
    lv_obj_set_width(ui_serial, 72);
    lv_obj_set_height(ui_serial, 72);
    lv_obj_set_x(ui_serial, -18);
    lv_obj_set_y(ui_serial, 2);
    lv_obj_set_align(ui_serial, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_serial, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_serial, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_serial, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_serial, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_serial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_serial, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_serial, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_serial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_serial, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_serial, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_serial, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_serial, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_serial, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor(ui_serial, lv_color_hex(0x4F4F4F), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_serial, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_wifi = lv_imgbtn_create(ui_apps);
    lv_imgbtn_set_src(ui_wifi, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wifiapp_png, NULL);
    lv_imgbtn_set_src(ui_wifi, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_wifiapp_png, NULL);
    lv_imgbtn_set_src(ui_wifi, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_wifiapp_png, NULL);
    lv_imgbtn_set_src(ui_wifi, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_wifiapp_png, NULL);
    lv_obj_set_width(ui_wifi, 72);
    lv_obj_set_height(ui_wifi, 72);
    lv_obj_set_x(ui_wifi, -18);
    lv_obj_set_y(ui_wifi, 2);
    lv_obj_set_align(ui_wifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi, LV_OBJ_FLAG_PRESS_LOCK);      /// Flags
    lv_obj_set_style_radius(ui_wifi, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_wifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_wifi, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_wifi, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_wifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_wifi, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_wifi, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_wifi, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_wifi, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_wifi, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor(ui_wifi, lv_color_hex(0x4F4F4F), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_wifi, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_content = lv_obj_create(ui_serialTerm);
    lv_obj_remove_style_all(ui_content);
    lv_obj_set_width(ui_content, 683);
    lv_obj_set_height(ui_content, 420);
    lv_obj_set_x(ui_content, 45);
    lv_obj_set_y(ui_content, 16);
    lv_obj_set_align(ui_content, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_content, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_content, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_content, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard2 = lv_keyboard_create(ui_content);
    lv_obj_set_width(ui_Keyboard2, 683);
    lv_obj_set_height(ui_Keyboard2, 210);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_Keyboard2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Keyboard2, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard2, 200, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Keyboard2, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard2, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard2, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Keyboard2, 200, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Keyboard2, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Keyboard2, 255, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Keyboard2, lv_color_hex(0x4C4C4C), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Keyboard2, 200, LV_PART_ITEMS | LV_STATE_PRESSED);

    ui_Input = lv_textarea_create(ui_content);
    lv_obj_set_width(ui_Input, 684);
    lv_obj_set_height(ui_Input, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Input, -8);
    lv_obj_set_y(ui_Input, 274);
    lv_textarea_set_placeholder_text(ui_Input, "ENTER CMD...");
    lv_textarea_set_one_line(ui_Input, true);
    lv_obj_add_state(ui_Input, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_text_color(ui_Input, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Input, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Input, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Input, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Input, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Input, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Input, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Input, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_width(ui_Input, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_Input, 8192, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_Input, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_Input, 8192, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Input, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Input, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Input, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_output = lv_textarea_create(ui_content);
    lv_obj_set_width(ui_output, 684);
    lv_obj_set_height(ui_output, 350);
    lv_textarea_set_placeholder_text(ui_output, "Output shows here");
    lv_obj_set_style_text_font(ui_output, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_output, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_output, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_output, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_output, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_output, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_output, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_output, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_output, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_serialTerm);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 800);
    lv_obj_set_height(ui_Container3, 480);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_serialPrefs = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_serialPrefs, 200);
    lv_obj_set_height(ui_serialPrefs, 200);
    lv_obj_set_align(ui_serialPrefs, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_serialPrefs, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_serialPrefs, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_serialPrefs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_serialPrefs, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_serialPrefs, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_serialPrefs, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_serialPrefs, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_serialPrefs, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_serialPrefs, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_baudrate = lv_dropdown_create(ui_serialPrefs);
    lv_dropdown_set_options(ui_baudrate, "9600\n115200");
    lv_obj_set_width(ui_baudrate, 140);
    lv_obj_set_height(ui_baudrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_baudrate, 51);
    lv_obj_set_y(ui_baudrate, 102);
    lv_obj_add_flag(ui_baudrate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_baudrate, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_baudrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_baudrate, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_baudrate, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_baudrate, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_baudrate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_baudrate, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_baudrate, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_baudrate, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_baudrate), lv_color_hex(0x808080),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_baudrate), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_dropdown_get_list(ui_baudrate), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_baudrate), lv_color_hex(0x3C3C3C),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_baudrate), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_baudrate), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_baudrate), 100,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_serialset = lv_dropdown_create(ui_serialPrefs);
    lv_dropdown_set_options(ui_serialset, "Serial0\nSerial1\nSerial2");
    lv_obj_set_width(ui_serialset, 140);
    lv_obj_set_height(ui_serialset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_serialset, 0);
    lv_obj_set_y(ui_serialset, 30);
    lv_obj_set_align(ui_serialset, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_serialset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_serialset, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_serialset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_serialset, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_serialset, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_serialset, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_serialset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_serialset, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_serialset, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_serialset, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_serialset), lv_color_hex(0x808080),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_serialset), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_dropdown_get_list(ui_serialset), 4,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_serialset), lv_color_hex(0x3C3C3C),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_serialset), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_serialset), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_serialset), 100,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SerialSetAccept = lv_btn_create(ui_serialPrefs);
    lv_obj_set_width(ui_SerialSetAccept, 124);
    lv_obj_set_height(ui_SerialSetAccept, 35);
    lv_obj_set_x(ui_SerialSetAccept, -16);
    lv_obj_set_y(ui_SerialSetAccept, 53);
    lv_obj_set_align(ui_SerialSetAccept, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SerialSetAccept, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SerialSetAccept, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SerialSetAccept, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SerialSetAccept, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_backBtn);
    ui_object_set_themeable_style_property(ui_SerialSetAccept, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_backBtn);
    ui_object_set_themeable_style_property(ui_SerialSetAccept, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_btnBorder);
    ui_object_set_themeable_style_property(ui_SerialSetAccept, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_btnBorder);

    ui_okBtnLabel = lv_label_create(ui_SerialSetAccept);
    lv_obj_set_width(ui_okBtnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_okBtnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_okBtnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_okBtnLabel, "Ok");

    lv_obj_add_event_cb(ui_wifi, ui_event_wifi, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_Input);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Input, ui_event_Input, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_output, ui_event_output, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SerialSetAccept, ui_event_SerialSetAccept, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_serialTerm, ui_event_serialTerm, LV_EVENT_ALL, NULL);
    uic_serialTerm = ui_serialTerm;
    uic_status = ui_status;
    uic_clock = ui_clock;
    uic_wifistat = ui_wifistat;
    uic_appname = ui_appname;
    uic_apps = ui_apps;
    uic_serial = ui_serial;
    uic_wifi = ui_wifi;
    uic_content = ui_content;
    uic_Input = ui_Input;
    uic_output = ui_output;
    uic_serialPrefs = ui_serialPrefs;
    uic_baudrate = ui_baudrate;
    uic_serialset = ui_serialset;
    uic_SerialSetAccept = ui_SerialSetAccept;
    uic_okBtnLabel = ui_okBtnLabel;

}

void ui_serialTerm_screen_destroy(void)
{
    if(ui_serialTerm) lv_obj_del(ui_serialTerm);
    terminal_screen_active = false;
    // NULL screen variables
    uic_serialTerm = NULL;
    ui_serialTerm = NULL;
    uic_status = NULL;
    ui_status = NULL;
    uic_clock = NULL;
    ui_clock = NULL;
    ui_Container1 = NULL;
    ui_wifistr = NULL;
    uic_wifistat = NULL;
    ui_wifistat = NULL;
    uic_appname = NULL;
    ui_appname = NULL;
    uic_apps = NULL;
    ui_apps = NULL;
    uic_serial = NULL;
    ui_serial = NULL;
    uic_wifi = NULL;
    ui_wifi = NULL;
    uic_content = NULL;
    ui_content = NULL;
    ui_Keyboard2 = NULL;
    uic_Input = NULL;
    ui_Input = NULL;
    uic_output = NULL;
    ui_output = NULL;
    ui_Container3 = NULL;
    uic_serialPrefs = NULL;
    ui_serialPrefs = NULL;
    uic_baudrate = NULL;
    ui_baudrate = NULL;
    uic_serialset = NULL;
    ui_serialset = NULL;
    uic_SerialSetAccept = NULL;
    ui_SerialSetAccept = NULL;
    uic_okBtnLabel = NULL;
    ui_okBtnLabel = NULL;

}
