// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: cosik

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_background[2] = {0x000000, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_background[2] = {200, 200};

const ui_theme_variable_t _ui_theme_color_borderColor[2] = {0x000000, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_borderColor[2] = {200, 200};

const ui_theme_variable_t _ui_theme_color_text[2] = {0x808080, 0x808080};
const ui_theme_variable_t _ui_theme_alpha_text[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_backBtn[2] = {0x3C3C3C, 0x3C3C3C};
const ui_theme_variable_t _ui_theme_alpha_backBtn[2] = {100, 100};

const ui_theme_variable_t _ui_theme_color_btnBorder[2] = {0x000000, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_btnBorder[2] = {100, 100};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

