// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: cosik

#include "ui.h"

lv_obj_t * uic_ConnectionStat;
lv_obj_t * uic_connStat;
lv_obj_t * uic_connect;
lv_obj_t * uic_disconnect;
lv_obj_t * uic_ssid;
lv_obj_t * uic_NetConn;
lv_obj_t * ui_WifiSettings = NULL;
lv_obj_t * ui_status1 = NULL;
lv_obj_t * ui_clock1 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_wifistr1 = NULL;
lv_obj_t * ui_wifistat1 = NULL;
lv_obj_t * ui_appname1 = NULL;
lv_obj_t * ui_apps1 = NULL;
lv_obj_t * ui_serial1 = NULL;
lv_obj_t * ui_wifi1 = NULL;
lv_obj_t * ui_content1 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_NetConn = NULL;
lv_obj_t * ui_ssid = NULL;
lv_obj_t * ui_pass = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_disconnect = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_connect = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_connStat = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Spinner2 = NULL;
lv_obj_t * ui_ConnectionStat = NULL;
// event funtions
void ui_event_WifiSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_label_set_property(ui_appname, _UI_LABEL_PROPERTY_TEXT, "WiFi Settings");
    }
}

void ui_event_serial1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_serialTerm, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_serialTerm_screen_init);
    }
}

void ui_event_ssid(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_pass);
    }
}

void ui_event_pass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_disconnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        disconnectWiFi(e);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_connect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        connectWiFi(e);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Container8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// build funtions

void ui_WifiSettings_screen_init(void)
{
    ui_WifiSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WifiSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_WifiSettings, &ui_img_backblue800x480_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status1 = lv_obj_create(ui_WifiSettings);
    lv_obj_set_width(ui_status1, 800);
    lv_obj_set_height(ui_status1, 40);
    lv_obj_set_align(ui_status1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_status1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_status1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_status1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_status1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_status1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_status1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_status1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_status1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clock1 = lv_label_create(ui_status1);
    lv_obj_set_width(ui_clock1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clock1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clock1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clock1, "%clock%");
    lv_obj_set_style_text_color(ui_clock1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clock1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_clock1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clock1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_status1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 150);
    lv_obj_set_height(ui_Container2, 40);
    lv_obj_set_x(ui_Container2, 20);
    lv_obj_set_y(ui_Container2, 0);
    lv_obj_set_align(ui_Container2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifistr1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_wifistr1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifistr1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifistr1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_wifistr1, "%wifi%");
    lv_obj_set_style_text_color(ui_wifistr1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifistr1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_wifistr1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifistr1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifistat1 = lv_img_create(ui_Container2);
    lv_img_set_src(ui_wifistat1, &ui_img_1149142576);
    lv_obj_set_width(ui_wifistat1, 32);
    lv_obj_set_height(ui_wifistat1, 32);
    lv_obj_set_align(ui_wifistat1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_wifistat1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifistat1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_appname1 = lv_label_create(ui_status1);
    lv_obj_set_width(ui_appname1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_appname1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_appname1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_appname1, "WiFi Settings");
    lv_obj_set_style_text_color(ui_appname1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_appname1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_appname1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_appname1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_apps1 = lv_obj_create(ui_WifiSettings);
    lv_obj_set_width(ui_apps1, 90);
    lv_obj_set_height(ui_apps1, 430);
    lv_obj_set_x(ui_apps1, 0);
    lv_obj_set_y(ui_apps1, 20);
    lv_obj_set_align(ui_apps1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_apps1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_apps1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_apps1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_apps1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_apps1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_apps1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_apps1, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_apps1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_apps1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_apps1, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_serial1 = lv_imgbtn_create(ui_apps1);
    lv_imgbtn_set_src(ui_serial1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1659073291, NULL);
    lv_imgbtn_set_src(ui_serial1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1659073291, NULL);
    lv_imgbtn_set_src(ui_serial1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_1659073291, NULL);
    lv_imgbtn_set_src(ui_serial1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_1659073291, NULL);
    lv_obj_set_width(ui_serial1, 72);
    lv_obj_set_height(ui_serial1, 72);
    lv_obj_set_x(ui_serial1, -18);
    lv_obj_set_y(ui_serial1, 2);
    lv_obj_set_align(ui_serial1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_serial1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_radius(ui_serial1, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_serial1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_serial1, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_serial1, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_serial1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_serial1, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_serial1, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_serial1, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_serial1, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_serial1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor(ui_serial1, lv_color_hex(0x4F4F4F), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_serial1, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_wifi1 = lv_imgbtn_create(ui_apps1);
    lv_imgbtn_set_src(ui_wifi1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wifiapp_png, NULL);
    lv_imgbtn_set_src(ui_wifi1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_wifiapp_png, NULL);
    lv_imgbtn_set_src(ui_wifi1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_wifiapp_png, NULL);
    lv_imgbtn_set_src(ui_wifi1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_wifiapp_png, NULL);
    lv_obj_set_width(ui_wifi1, 72);
    lv_obj_set_height(ui_wifi1, 72);
    lv_obj_set_x(ui_wifi1, -18);
    lv_obj_set_y(ui_wifi1, 2);
    lv_obj_set_align(ui_wifi1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_wifi1, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_wifi1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK);      /// Flags
    lv_obj_set_style_radius(ui_wifi1, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_wifi1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_wifi1, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_wifi1, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_wifi1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_wifi1, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_wifi1, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_wifi1, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_wifi1, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_wifi1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor(ui_wifi1, lv_color_hex(0x4F4F4F), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_wifi1, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_content1 = lv_obj_create(ui_WifiSettings);
    lv_obj_remove_style_all(ui_content1);
    lv_obj_set_width(ui_content1, 683);
    lv_obj_set_height(ui_content1, 420);
    lv_obj_set_x(ui_content1, 45);
    lv_obj_set_y(ui_content1, 17);
    lv_obj_set_align(ui_content1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_content1, LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);
    lv_obj_set_flex_align(ui_content1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_content1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_content1);
    lv_obj_set_width(ui_Keyboard1, 683);
    lv_obj_set_height(ui_Keyboard1, 210);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_Keyboard1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 200, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Keyboard1, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 200, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Keyboard1, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x4C4C4C), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 200, LV_PART_ITEMS | LV_STATE_PRESSED);

    ui_Container4 = lv_obj_create(ui_content1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 678);
    lv_obj_set_height(ui_Container4, 201);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image1, &ui_img_548092219);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 75);
    lv_obj_set_y(ui_Image1, 54);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Image1, 1, -1000);
    lv_img_set_zoom(ui_Image1, 250);

    ui_Container5 = lv_obj_create(ui_Container4);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 456);
    lv_obj_set_height(ui_Container5, 199);
    lv_obj_set_x(ui_Container5, 71);
    lv_obj_set_y(ui_Container5, -1);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NetConn = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_NetConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NetConn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetConn, "%NET%");
    lv_obj_set_style_text_color(ui_NetConn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetConn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetConn, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssid = lv_textarea_create(ui_Container5);
    lv_obj_set_width(ui_ssid, 400);
    lv_obj_set_height(ui_ssid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ssid, 0);
    lv_obj_set_y(ui_ssid, 150);
    lv_obj_set_align(ui_ssid, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ssid, "SSID");
    lv_textarea_set_one_line(ui_ssid, true);
    lv_obj_add_state(ui_ssid, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_text_color(ui_ssid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ssid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ssid, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ssid, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ssid, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ssid, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ssid, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ssid, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_ssid, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ssid, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ssid, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_pass = lv_textarea_create(ui_Container5);
    lv_obj_set_width(ui_pass, 400);
    lv_obj_set_height(ui_pass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pass, -30);
    lv_obj_set_y(ui_pass, 198);
    lv_obj_set_align(ui_pass, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_pass, "Password");
    lv_textarea_set_one_line(ui_pass, true);
    lv_textarea_set_password_mode(ui_pass, true);
    lv_obj_add_state(ui_pass, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_text_color(ui_pass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pass, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_pass, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pass, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pass, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_pass, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pass, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pass, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Container5);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 410);
    lv_obj_set_height(ui_Container6, 50);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_disconnect = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_disconnect, 195);
    lv_obj_set_height(ui_disconnect, 50);
    lv_obj_set_x(ui_disconnect, -97);
    lv_obj_set_y(ui_disconnect, 81);
    lv_obj_set_align(ui_disconnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_disconnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_disconnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_disconnect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_disconnect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_disconnect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_borderColor);
    ui_object_set_themeable_style_property(ui_disconnect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_borderColor);

    ui_Label2 = lv_label_create(ui_disconnect);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Disconnect");
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connect = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_connect, 195);
    lv_obj_set_height(ui_connect, 50);
    lv_obj_set_align(ui_connect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_connect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_connect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_connect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_connect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_connect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_borderColor);
    ui_object_set_themeable_style_property(ui_connect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_borderColor);

    ui_Label3 = lv_label_create(ui_connect);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Connect");
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_WifiSettings);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 800);
    lv_obj_set_height(ui_Container8, 480);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container8, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container8, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container8, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connStat = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_connStat, 600);
    lv_obj_set_height(ui_connStat, 420);
    lv_obj_set_align(ui_connStat, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_connStat, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_connStat, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_connStat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_connStat, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_connStat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connStat, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_connStat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_connStat, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_connStat, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_connStat);
    lv_img_set_src(ui_Image2, &ui_img_548092219);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner2 = lv_spinner_create(ui_connStat, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 80);
    lv_obj_set_height(ui_Spinner2, 80);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_ConnectionStat = lv_label_create(ui_connStat);
    lv_obj_set_width(ui_ConnectionStat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectionStat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConnectionStat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectionStat, "%ConnStat%");
    lv_obj_set_style_text_color(ui_ConnectionStat, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectionStat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConnectionStat, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_serial1, ui_event_serial1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_ssid);
    lv_obj_add_event_cb(ui_ssid, ui_event_ssid, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pass, ui_event_pass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_disconnect, ui_event_disconnect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_connect, ui_event_connect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiSettings, ui_event_WifiSettings, LV_EVENT_ALL, NULL);
    uic_NetConn = ui_NetConn;
    uic_ssid = ui_ssid;
    uic_disconnect = ui_disconnect;
    uic_connect = ui_connect;
    uic_connStat = ui_connStat;
    uic_ConnectionStat = ui_ConnectionStat;

}

void ui_WifiSettings_screen_destroy(void)
{
    if(ui_WifiSettings) lv_obj_del(ui_WifiSettings);

    // NULL screen variables
    ui_WifiSettings = NULL;
    ui_status1 = NULL;
    ui_clock1 = NULL;
    ui_Container2 = NULL;
    ui_wifistr1 = NULL;
    ui_wifistat1 = NULL;
    ui_appname1 = NULL;
    ui_apps1 = NULL;
    ui_serial1 = NULL;
    ui_wifi1 = NULL;
    ui_content1 = NULL;
    ui_Keyboard1 = NULL;
    ui_Container4 = NULL;
    ui_Image1 = NULL;
    ui_Container5 = NULL;
    uic_NetConn = NULL;
    ui_NetConn = NULL;
    uic_ssid = NULL;
    ui_ssid = NULL;
    ui_pass = NULL;
    ui_Container6 = NULL;
    uic_disconnect = NULL;
    ui_disconnect = NULL;
    ui_Label2 = NULL;
    uic_connect = NULL;
    ui_connect = NULL;
    ui_Label3 = NULL;
    ui_Container8 = NULL;
    uic_connStat = NULL;
    ui_connStat = NULL;
    ui_Image2 = NULL;
    ui_Spinner2 = NULL;
    uic_ConnectionStat = NULL;
    ui_ConnectionStat = NULL;

}
