// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: cosik

#include "ui.h"

lv_obj_t * uic_ConnectionStat;
lv_obj_t * uic_connStat;
lv_obj_t * uic_ConnPopup;
lv_obj_t * uic_connect;
lv_obj_t * uic_disconnect;
lv_obj_t * uic_ContainerButtons;
lv_obj_t * uic_SSID;
lv_obj_t * uic_NetConn;
lv_obj_t * uic_ContainerForm;
lv_obj_t * uic_WifiIcon;
lv_obj_t * uic_WifiSet;
lv_obj_t * uic_KeyboardWiFi;
lv_obj_t * uic_content;
lv_obj_t * uic_wifi;
lv_obj_t * uic_apps;
lv_obj_t * uic_appname;
lv_obj_t * uic_wifistat;
lv_obj_t * uic_wifistr;
lv_obj_t * uic_wifiStateArea;
lv_obj_t * uic_clock;
lv_obj_t * uic_statusArea;
lv_obj_t * ui_WifiSettings = NULL;
lv_obj_t * ui_statusArea = NULL;
lv_obj_t * ui_clock = NULL;
lv_obj_t * ui_wifiStateArea = NULL;
lv_obj_t * ui_wifistr = NULL;
lv_obj_t * ui_wifistat = NULL;
lv_obj_t * ui_appname = NULL;
lv_obj_t * ui_apps = NULL;
lv_obj_t * ui_wifi = NULL;
lv_obj_t * ui_content = NULL;
lv_obj_t * ui_KeyboardWiFi = NULL;
lv_obj_t * ui_WifiSet = NULL;
lv_obj_t * ui_WifiIcon = NULL;
lv_obj_t * ui_ContainerForm = NULL;
lv_obj_t * ui_NetConn = NULL;
lv_obj_t * ui_SSID = NULL;
lv_obj_t * ui_PASS = NULL;
lv_obj_t * ui_ContainerButtons = NULL;
lv_obj_t * ui_disconnect = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_connect = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_ConnPopup = NULL;
lv_obj_t * ui_connStat = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Spinner2 = NULL;
lv_obj_t * ui_ConnectionStat = NULL;
// event funtions
void ui_event_SSID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardWiFi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_KeyboardWiFi,  ui_SSID);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        _ui_keyboard_set_target(ui_KeyboardWiFi,  ui_PASS);
    }
}

void ui_event_PASS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardWiFi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_KeyboardWiFi,  ui_PASS);
    }
}

void ui_event_disconnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        disconnectWiFi(e);
        _ui_flag_modify(ui_KeyboardWiFi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_connect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardWiFi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ConnPopup, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_ConnPopup, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        connectWiFi(e);
    }
}

// build funtions

void ui_WifiSettings_screen_init(void)
{
    ui_WifiSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WifiSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiSettings, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_WifiSettings, &ui_img_backblue800x480_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusArea = lv_obj_create(ui_WifiSettings);
    lv_obj_set_width(ui_statusArea, 800);
    lv_obj_set_height(ui_statusArea, 40);
    lv_obj_set_align(ui_statusArea, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_statusArea, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_statusArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statusArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_statusArea, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_statusArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_statusArea, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_statusArea, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clock = lv_label_create(ui_statusArea);
    lv_obj_set_width(ui_clock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clock, "%clock%");
    lv_obj_set_style_text_color(ui_clock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_clock, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clock, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiStateArea = lv_obj_create(ui_statusArea);
    lv_obj_remove_style_all(ui_wifiStateArea);
    lv_obj_set_width(ui_wifiStateArea, 200);
    lv_obj_set_height(ui_wifiStateArea, 40);
    lv_obj_set_x(ui_wifiStateArea, 20);
    lv_obj_set_y(ui_wifiStateArea, 0);
    lv_obj_set_align(ui_wifiStateArea, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_wifiStateArea, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wifiStateArea, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifiStateArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifistr = lv_label_create(ui_wifiStateArea);
    lv_obj_set_width(ui_wifistr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifistr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifistr, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_wifistr, "%wifi%");
    lv_obj_set_style_text_color(ui_wifistr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifistr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_wifistr, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifistr, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifistat = lv_img_create(ui_wifiStateArea);
    lv_img_set_src(ui_wifistat, &ui_img_1149142576);
    lv_obj_set_width(ui_wifistat, 32);
    lv_obj_set_height(ui_wifistat, 32);
    lv_obj_set_align(ui_wifistat, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_wifistat, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifistat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_appname = lv_label_create(ui_statusArea);
    lv_obj_set_width(ui_appname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_appname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_appname, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_appname, "WiFi Settings");
    lv_obj_set_style_text_color(ui_appname, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_appname, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_appname, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_appname, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_apps = lv_obj_create(ui_WifiSettings);
    lv_obj_set_width(ui_apps, 90);
    lv_obj_set_height(ui_apps, 430);
    lv_obj_set_x(ui_apps, 0);
    lv_obj_set_y(ui_apps, 20);
    lv_obj_set_align(ui_apps, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_apps, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_apps, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_apps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_apps, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_apps, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_apps, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_apps, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_apps, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_apps, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_apps, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi = lv_imgbtn_create(ui_apps);
    lv_imgbtn_set_src(ui_wifi, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wifiapp_png, NULL);
    lv_imgbtn_set_src(ui_wifi, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_wifiapp_png, NULL);
    lv_imgbtn_set_src(ui_wifi, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_wifiapp_png, NULL);
    lv_imgbtn_set_src(ui_wifi, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_wifiapp_png, NULL);
    lv_obj_set_width(ui_wifi, 72);
    lv_obj_set_height(ui_wifi, 72);
    lv_obj_set_x(ui_wifi, -18);
    lv_obj_set_y(ui_wifi, 2);
    lv_obj_set_align(ui_wifi, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_wifi, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_wifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK);      /// Flags
    lv_obj_set_style_radius(ui_wifi, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_wifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_wifi, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_wifi, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_wifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_wifi, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_wifi, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_wifi, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_wifi, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_wifi, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor(ui_wifi, lv_color_hex(0x4F4F4F), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_wifi, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_content = lv_obj_create(ui_WifiSettings);
    lv_obj_remove_style_all(ui_content);
    lv_obj_set_width(ui_content, 683);
    lv_obj_set_height(ui_content, 420);
    lv_obj_set_x(ui_content, 45);
    lv_obj_set_y(ui_content, 17);
    lv_obj_set_align(ui_content, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_content, LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);
    lv_obj_set_flex_align(ui_content, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_content, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KeyboardWiFi = lv_keyboard_create(ui_content);
    lv_obj_set_width(ui_KeyboardWiFi, 683);
    lv_obj_set_height(ui_KeyboardWiFi, 210);
    lv_obj_set_align(ui_KeyboardWiFi, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_KeyboardWiFi, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_KeyboardWiFi, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardWiFi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardWiFi, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_KeyboardWiFi, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardWiFi, 200, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_KeyboardWiFi, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_KeyboardWiFi, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardWiFi, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_KeyboardWiFi, 200, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_KeyboardWiFi, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_KeyboardWiFi, 255, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_KeyboardWiFi, lv_color_hex(0x4C4C4C), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_KeyboardWiFi, 200, LV_PART_ITEMS | LV_STATE_PRESSED);

    ui_WifiSet = lv_obj_create(ui_content);
    lv_obj_remove_style_all(ui_WifiSet);
    lv_obj_set_width(ui_WifiSet, 678);
    lv_obj_set_height(ui_WifiSet, 201);
    lv_obj_set_align(ui_WifiSet, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiSet, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_WifiSet, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_WifiSet, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiIcon = lv_img_create(ui_WifiSet);
    lv_img_set_src(ui_WifiIcon, &ui_img_548092219);
    lv_obj_set_width(ui_WifiIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiIcon, 75);
    lv_obj_set_y(ui_WifiIcon, 54);
    lv_obj_add_flag(ui_WifiIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_WifiIcon, 1, -1000);
    lv_img_set_zoom(ui_WifiIcon, 250);

    ui_ContainerForm = lv_obj_create(ui_WifiSet);
    lv_obj_remove_style_all(ui_ContainerForm);
    lv_obj_set_width(ui_ContainerForm, 456);
    lv_obj_set_height(ui_ContainerForm, 199);
    lv_obj_set_x(ui_ContainerForm, 71);
    lv_obj_set_y(ui_ContainerForm, -1);
    lv_obj_set_align(ui_ContainerForm, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerForm, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_ContainerForm, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerForm, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NetConn = lv_label_create(ui_ContainerForm);
    lv_obj_set_width(ui_NetConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NetConn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetConn, "%NET%");
    lv_obj_set_style_text_color(ui_NetConn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetConn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetConn, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSID = lv_textarea_create(ui_ContainerForm);
    lv_obj_set_width(ui_SSID, 400);
    lv_obj_set_height(ui_SSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SSID, 0);
    lv_obj_set_y(ui_SSID, 150);
    lv_obj_set_align(ui_SSID, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_SSID, "SSID");
    lv_textarea_set_one_line(ui_SSID, true);
    lv_obj_add_state(ui_SSID, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_text_color(ui_SSID, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSID, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SSID, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SSID, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SSID, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SSID, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SSID, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_SSID, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSID, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_PASS = lv_textarea_create(ui_ContainerForm);
    lv_obj_set_width(ui_PASS, 400);
    lv_obj_set_height(ui_PASS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PASS, -30);
    lv_obj_set_y(ui_PASS, 198);
    lv_obj_set_align(ui_PASS, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PASS, "Password");
    lv_textarea_set_one_line(ui_PASS, true);
    lv_textarea_set_password_mode(ui_PASS, true);
    lv_obj_add_state(ui_PASS, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_text_color(ui_PASS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PASS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PASS, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PASS, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PASS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PASS, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PASS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PASS, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_PASS, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PASS, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PASS, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ContainerButtons = lv_obj_create(ui_ContainerForm);
    lv_obj_remove_style_all(ui_ContainerButtons);
    lv_obj_set_width(ui_ContainerButtons, 410);
    lv_obj_set_height(ui_ContainerButtons, 50);
    lv_obj_set_align(ui_ContainerButtons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerButtons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerButtons, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerButtons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_disconnect = lv_btn_create(ui_ContainerButtons);
    lv_obj_set_width(ui_disconnect, 195);
    lv_obj_set_height(ui_disconnect, 50);
    lv_obj_set_x(ui_disconnect, -97);
    lv_obj_set_y(ui_disconnect, 81);
    lv_obj_set_align(ui_disconnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_disconnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_disconnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_disconnect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_disconnect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_disconnect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_borderColor);
    ui_object_set_themeable_style_property(ui_disconnect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_borderColor);

    ui_Label2 = lv_label_create(ui_disconnect);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Disconnect");
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connect = lv_btn_create(ui_ContainerButtons);
    lv_obj_set_width(ui_connect, 195);
    lv_obj_set_height(ui_connect, 50);
    lv_obj_set_align(ui_connect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_connect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_connect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_connect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_connect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_connect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_borderColor);
    ui_object_set_themeable_style_property(ui_connect, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_borderColor);

    ui_Label3 = lv_label_create(ui_connect);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Connect");
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnPopup = lv_obj_create(ui_WifiSettings);
    lv_obj_remove_style_all(ui_ConnPopup);
    lv_obj_set_width(ui_ConnPopup, 800);
    lv_obj_set_height(ui_ConnPopup, 480);
    lv_obj_set_align(ui_ConnPopup, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ConnPopup, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_ConnPopup, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ConnPopup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConnPopup, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnPopup, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connStat = lv_obj_create(ui_ConnPopup);
    lv_obj_set_width(ui_connStat, 600);
    lv_obj_set_height(ui_connStat, 420);
    lv_obj_set_align(ui_connStat, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_connStat, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_connStat, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_connStat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_connStat, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_connStat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connStat, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_connStat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_connStat, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_connStat, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_connStat);
    lv_img_set_src(ui_Image2, &ui_img_548092219);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner2 = lv_spinner_create(ui_connStat, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 80);
    lv_obj_set_height(ui_Spinner2, 80);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_ConnectionStat = lv_label_create(ui_connStat);
    lv_obj_set_width(ui_ConnectionStat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectionStat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConnectionStat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectionStat, "%ConnStat%");
    lv_obj_set_style_text_color(ui_ConnectionStat, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectionStat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConnectionStat, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_KeyboardWiFi, ui_SSID);
    lv_obj_add_event_cb(ui_SSID, ui_event_SSID, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PASS, ui_event_PASS, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_disconnect, ui_event_disconnect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_connect, ui_event_connect, LV_EVENT_ALL, NULL);
    uic_statusArea = ui_statusArea;
    uic_clock = ui_clock;
    uic_wifiStateArea = ui_wifiStateArea;
    uic_wifistr = ui_wifistr;
    uic_wifistat = ui_wifistat;
    uic_appname = ui_appname;
    uic_apps = ui_apps;
    uic_wifi = ui_wifi;
    uic_content = ui_content;
    uic_KeyboardWiFi = ui_KeyboardWiFi;
    uic_WifiSet = ui_WifiSet;
    uic_WifiIcon = ui_WifiIcon;
    uic_ContainerForm = ui_ContainerForm;
    uic_NetConn = ui_NetConn;
    uic_SSID = ui_SSID;
    uic_ContainerButtons = ui_ContainerButtons;
    uic_disconnect = ui_disconnect;
    uic_connect = ui_connect;
    uic_ConnPopup = ui_ConnPopup;
    uic_connStat = ui_connStat;
    uic_ConnectionStat = ui_ConnectionStat;

}

void ui_WifiSettings_screen_destroy(void)
{
    if(ui_WifiSettings) lv_obj_del(ui_WifiSettings);

    // NULL screen variables
    ui_WifiSettings = NULL;
    uic_statusArea = NULL;
    ui_statusArea = NULL;
    uic_clock = NULL;
    ui_clock = NULL;
    uic_wifiStateArea = NULL;
    ui_wifiStateArea = NULL;
    uic_wifistr = NULL;
    ui_wifistr = NULL;
    uic_wifistat = NULL;
    ui_wifistat = NULL;
    uic_appname = NULL;
    ui_appname = NULL;
    uic_apps = NULL;
    ui_apps = NULL;
    uic_wifi = NULL;
    ui_wifi = NULL;
    uic_content = NULL;
    ui_content = NULL;
    uic_KeyboardWiFi = NULL;
    ui_KeyboardWiFi = NULL;
    uic_WifiSet = NULL;
    ui_WifiSet = NULL;
    uic_WifiIcon = NULL;
    ui_WifiIcon = NULL;
    uic_ContainerForm = NULL;
    ui_ContainerForm = NULL;
    uic_NetConn = NULL;
    ui_NetConn = NULL;
    uic_SSID = NULL;
    ui_SSID = NULL;
    ui_PASS = NULL;
    uic_ContainerButtons = NULL;
    ui_ContainerButtons = NULL;
    uic_disconnect = NULL;
    ui_disconnect = NULL;
    ui_Label2 = NULL;
    uic_connect = NULL;
    ui_connect = NULL;
    ui_Label3 = NULL;
    uic_ConnPopup = NULL;
    ui_ConnPopup = NULL;
    uic_connStat = NULL;
    ui_connStat = NULL;
    ui_Image2 = NULL;
    ui_Spinner2 = NULL;
    uic_ConnectionStat = NULL;
    ui_ConnectionStat = NULL;

}
