// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: cosik

#ifndef UI_WIFISETTINGS_H
#define UI_WIFISETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiSettings
extern void ui_WifiSettings_screen_init(void);
extern void ui_WifiSettings_screen_destroy(void);
extern void ui_event_WifiSettings(lv_event_t * e);
extern lv_obj_t * ui_WifiSettings;
extern lv_obj_t * ui_status1;
extern lv_obj_t * ui_clock1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_wifistr1;
extern lv_obj_t * ui_wifistat1;
extern lv_obj_t * ui_appname1;
extern lv_obj_t * ui_apps1;
extern void ui_event_serial1(lv_event_t * e);
extern lv_obj_t * ui_serial1;
extern lv_obj_t * ui_wifi1;
extern lv_obj_t * ui_content1;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_NetConn;
extern void ui_event_ssid(lv_event_t * e);
extern lv_obj_t * ui_ssid;
extern void ui_event_pass(lv_event_t * e);
extern lv_obj_t * ui_pass;
extern lv_obj_t * ui_Container6;
extern void ui_event_disconnect(lv_event_t * e);
extern lv_obj_t * ui_disconnect;
extern lv_obj_t * ui_Label2;
extern void ui_event_connect(lv_event_t * e);
extern lv_obj_t * ui_connect;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_connStat;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_ConnectionStat;
// CUSTOM VARIABLES
extern lv_obj_t * uic_NetConn;
extern lv_obj_t * uic_ssid;
extern lv_obj_t * uic_disconnect;
extern lv_obj_t * uic_connect;
extern lv_obj_t * uic_connStat;
extern lv_obj_t * uic_ConnectionStat;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

