// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: cosik

#ifndef UI_WIFISETTINGS_H
#define UI_WIFISETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiSettings
extern void ui_WifiSettings_screen_init(void);
extern void ui_WifiSettings_screen_destroy(void);
extern lv_obj_t * ui_WifiSettings;
extern lv_obj_t * ui_statusArea;
extern lv_obj_t * ui_clock;
extern lv_obj_t * ui_wifiStateArea;
extern lv_obj_t * ui_wifistr;
extern lv_obj_t * ui_wifistat;
extern lv_obj_t * ui_appname;
extern lv_obj_t * ui_apps;
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_content;
extern lv_obj_t * ui_KeyboardWiFi;
extern lv_obj_t * ui_WifiSet;
extern lv_obj_t * ui_WifiIcon;
extern lv_obj_t * ui_ContainerForm;
extern lv_obj_t * ui_NetConn;
extern void ui_event_SSID(lv_event_t * e);
extern lv_obj_t * ui_SSID;
extern void ui_event_PASS(lv_event_t * e);
extern lv_obj_t * ui_PASS;
extern lv_obj_t * ui_ContainerButtons;
extern void ui_event_disconnect(lv_event_t * e);
extern lv_obj_t * ui_disconnect;
extern lv_obj_t * ui_Label2;
extern void ui_event_connect(lv_event_t * e);
extern lv_obj_t * ui_connect;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_ConnPopup;
extern lv_obj_t * ui_connStat;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_ConnectionStat;
// CUSTOM VARIABLES
extern lv_obj_t * uic_statusArea;
extern lv_obj_t * uic_clock;
extern lv_obj_t * uic_wifiStateArea;
extern lv_obj_t * uic_wifistr;
extern lv_obj_t * uic_wifistat;
extern lv_obj_t * uic_appname;
extern lv_obj_t * uic_apps;
extern lv_obj_t * uic_wifi;
extern lv_obj_t * uic_content;
extern lv_obj_t * uic_KeyboardWiFi;
extern lv_obj_t * uic_WifiSet;
extern lv_obj_t * uic_WifiIcon;
extern lv_obj_t * uic_ContainerForm;
extern lv_obj_t * uic_NetConn;
extern lv_obj_t * uic_SSID;
extern lv_obj_t * uic_ContainerButtons;
extern lv_obj_t * uic_disconnect;
extern lv_obj_t * uic_connect;
extern lv_obj_t * uic_ConnPopup;
extern lv_obj_t * uic_connStat;
extern lv_obj_t * uic_ConnectionStat;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

